description: >
  This job always runs first

executor: default

parameters:
  to:
    type: string
    default: "World"
    description: "Hello to whom?"
steps:
  - greet:
      to: << parameters.to >>